---
- name: "Apache installation using docker"
  hosts: prod
  become: true
# vars:
#   ansible_sudo_pass: admin
  pre_tasks:
    - name: Install EPEL release
      package: name=epel-release state=present
      when: ansible_distribution=="CentOS"
    - name: install python pip
      yum: name=python-pip state=present update_cache=yes
    - name: Install docker python
      pip: name=docker-py
  tasks:
    - name: Create Apache conteneur
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
